### ISSUE TITLE
BC lasers and Power

### ISSUE THREAD

**Issue by Broninja69** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#107]
I am having an issue when using Golden kinesis pipes and BC lasers with using the assembly table. I have multiple lasers hooked up but it isn't providing the table with power. It also seems that the golden kinesis pipes are taking up a lot of power from the MJ producer but not actually using it and just wasting it.

**Comment by bmtagile** [comment]
can you provide a screenshot? the table in the 1.12 of the mod requires the lasers to point at the table and requires line of sight.  the previous version featured in the 1.7 infinity evolved pack did not have that requirement.

**Comment by Broninja69** [comment]
![1607466868934192402562100267786](https://user-images.githubusercontent.com/75677991/101549423-a7912500-397b-11eb-9533-aa9c0bfed807.jpg)
Also its hard to see, but the kinesis pipes are flickering with power. Im not sure if it's an issue with the pipes or lasers or a something else.

**Comment by Broninja69** [comment]
![16074671794854083321636677619450](https://user-images.githubusercontent.com/75677991/101549850-62212780-397c-11eb-996c-75458b76ef1b.jpg)
This is another view where it seems power isnt flowing through the pipes to the one on the bottom but its still working. Also it siphons a lot of my power instantly but doesn't put it anywhere. I think its taking too much power for some reason

**Comment by Broninja69** [comment]
![16074676027953777593597894669020](https://user-images.githubusercontent.com/75677991/101550467-5bdf7b00-397d-11eb-827a-21314438c7bd.jpg)
Arranged like that apparently works though

**Comment by bmtagile** [comment]
for the first 2 shots, the top row is too far away horizontally, if the table were one block further away from the lasers the top row will work.  it's just how the mod works.  if the lasers are adjacent to the table you are limited to one per side. with a one block gap you are limited to a 3x3 group on each side centered on the table.  with a 2 block gap it's 5x5 and so on.  I haven't tried to determine the range limit on that yet.  

The way i end up thinking of it, you create in your mind a cube centered on the table based on the gap between it and the lasers, the lasers only work when the tip of the laser touches a face of that cube.  It's nothing to do with the pack, it's how the mod works now.

**Comment by Broninja69** [comment]
Would you know about the issues with the lighting glitch or flickering of the kinesis pipes.

**Comment by bmtagile** [comment]
Kinesis pipes don't like loops, you can control that with pipe plugs they used to explode if you had loops but that along with the pipe transfer limits appears to not yet be implemented in 1.12. Other than that i'd have to watch it to offer anything.

**Comment by fabrossmann** [comment]
Since some players had this issue already, we decided to add an alternative to the Laser by using the Draconic Evolution Fusion Crafting. See #129.
