### ISSUE TITLE
Natura Logs -> Planks messed up

### ISSUE THREAD

**Issue by LittleCircles** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#125]
**General Info (please complete the following information):**
 - Modpack version: [e.g. 3.2.0] 3.4.1
 - Client or server: I tested on Server, but I assume its to client too.
 - Own modifications to the modpack: N/A

**Describe the bug**
It gives 4 planks per log on every natura wood of what I could see. 

**To Reproduce**
Check JEI for the Natura logs to planks recipe

**Comment by LittleCircles** [comment]
Sorry, its every Natura Logs to planks except for the Eucalyptus Wood

**Comment by fabrossmann** [comment]
Thanks for reporting, we will look into it!

**Comment by fabrossmann** [comment]
Fixed in Version 3.5.1
