### ISSUE TITLE
Agricraft seeds do not load in Garden Cloche

### ISSUE THREAD

**Issue by tweak42** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#128]
- Modpack version: 3.4.1
 - Client or server: single and multiplayer server

**Describe the bug**
Unable to load Agricraft and Natura seeds, Thaumcraft Cinderpearls in Garden Cloche

**To Reproduce**
Failed loading:  dirt with carrot seeds, barley, sand with sugarcane, cactus and cinderpearls. 

Note:
General Minecraft and Pam's Harvestcraft seeds appear to work.
Extra Utilities Red Orchid appears to work.

**Comment by fabrossmann** [comment]
Thank you for the report, we will look into it!

**Comment by SanderWxD** [comment]
Took a while but a fix is implemented in the current release.
