### ISSUE TITLE
Bronze item casing crafting problem

### ISSUE THREAD

**Issue by cavinnhobbes** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#138]
**General Info (please complete the following information):**
 - Modpack version: 3.4.1
 - Client or server: Server/Client
 - Own modifications to the modpack: None

**Describe the bug**
The recipe for 'bronze item casing' from IC2 seems to require 'brass plate' in the metal former to create as opposed to the usual bronze plate.

**To Reproduce**
1. Install modpack I guess.
2. Look at JEI, and look for the recipe to craft bronze item casing.

**Screenshots**
![image](https://user-images.githubusercontent.com/22580476/103323707-45738f00-4a12-11eb-9ca7-9b241b41f987.png)

**Comment by fabrossmann** [comment]
Already fixed in #123 and will be released in the upcoming update
