### ISSUE TITLE
Recipe conflicts and wrong names

### ISSUE THREAD

**Issue by Erani0** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#141]
- Modpack version: 3.5.0
 - Client or server: Myftb
 - Own modifications to the modpack: none
 
 Recipe Conficts:

 Hardened Truster 
 -Need Magmatic Dynamo

Leadstone Truster have the same recipe as Cryotheum coolant unit

Quests for jetpackts have the wrong names 

I Play Hardmode
not more at this time

**Comment by fabrossmann** [comment]
Fixed in Version 3.5.1
