### ISSUE TITLE
[3.5.0] [Magicbees] Rockin & Grounded Bee not producing their specialities

### ISSUE THREAD

**Issue by sk4zi** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#144]
Modpack version: 3.5.0 (Expert Mode)
Client or server: Both
Own modifications to the modpack: None

Rockin & Grounded Bee from Magicbees aren´t producing their specialities (Basalz Powder/Petrotheum Dust), despite JEI shownig a 9% Chance for them
 
I made them with a Genetic Template from Gendustry, Factors like Temp/Humidity/Flowers etc are not the Problem

**Comment by fabrossmann** [comment]
Hey thanks for reporting. It seems like these Magic Bees have to be in their exact favourite Biom, even with manipulated genes. See MagicBees/MagicBees#128 for more information.

**Comment by sk4zi** [comment]
Thx, found the Problem. Put a Hell Emulation Upgrade in the Apiary, which made it too hot. Should have double checked that
