### ISSUE TITLE
Iodine recipe consumes water container

### ISSUE THREAD

**Issue by kotkowski** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#145]
During iodine crafting, portable tank filled with water got consumed, crafting single iodine.

**General Info (please complete the following information):**
 - Modpack version: 3.4.1
 - Server

Description:
Water tank gets consumed during the crafting

**To Reproduce**
1. Get Pulverized Tin
2. Get Water Tank from Thermal Expansion (not sure if works with others)
3. Craft Iodine

**Comment by saovenn** [comment]
Hello,

I've checked it out ingame, this shouldn't happen, will fix it for the next update, thanks for reporting it 👍
