### ISSUE TITLE
Railcraft Boilers messing with your Inventory Leading to Dupings bugs and other Issues

### ISSUE THREAD

**Issue by ollah86** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#148]
**General Info (please complete the following information):**
 - Modpack version: 3.5.0 and below
 - Client or server:both

**Describe the bug**
i think the Video makes it Clear: https://www.youtube.com/watch?v=LTyBjp-LwKw&feature=youtu.be

**To Reproduce**

i think the Firestone is essential to reproduce

**Comment by Malien** [comment]
I think something of this kind is an old Railcraft 1.12 issue. I've had multiple issues with RC multi-block structures like that. Since R.I.P. Railcraft (CovertJaguar is nowhere to be found), this won't be fixed anytime soon.

**Comment by SanderWxD** [comment]
Since it look to me like a bug in the Railcraft mod itself, it is not something we can fix ourselves.
You could try reporting this bug with the Railcraft dev(s) to get it fixed.

Thanks for the report.
