### ISSUE TITLE
No recipe of copper ingots from copper blocks 

### ISSUE THREAD

**Issue by Plezha** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#149]
**General Info (please complete the following information):**
 - Modpack version: [e.g. 3.5.0]
 - Client or server: server
 - Own modifications to the modpack: none

**Describe the bug**
1. No recipe of copper ingots from copper blocks which i get from tinkers' smeltery (also mb some of other ones)

**To Reproduce**
E.g.:
1. Go to Indninity Evolved reloaded
2. Try to smelt copper ore in tinkers' smeltery, pour the liquid copper into a basin, then make ingots from copper blocks you got
3. See error.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Crash-log**
[If applicable, add a crash-log. Usually a "crash-[date]-[time]-server/client.txt"]

**Comment by Aracuron** [comment]
Applies to Client to.

**Comment by SanderWxD** [comment]
Recipe fixed in #146 
Thanks for reporting it.

**Comment by fabrossmann** [comment]
Fixed in Version 3.5.1
