### ISSUE TITLE
Game crash by search on jei and me

### ISSUE THREAD

**Issue by Erani0** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#154]
**General Info (please complete the following information):**
 - Modpack version: 3.5
 - Client or server:
 - Own modifications to the modpack:
 Tabbychat,LiteLoader and optifine

**Describe the bug**
By typing in jei "ma"  - "tra" - " con" 
Search on Me interface "re" 
All this crash the game

**Crash-log**
https://paste.myftb.de/qoroqelaki

The Edits on formfix.cfg made no change my game crash again.

**Comment by fabrossmann** [comment]
See Railcraft/Railcraft#1806. If that doesn't work, try to remove FoamFix until this issue is solved by Railcraft.

**Comment by Erani0** [comment]
Is set on false.
And no change i have now delete the formfix mod
And now no crash.
Is formfix Importen?

**Comment by fabrossmann** [comment]
Yes it is and it is not a problem with our pack and more likely with Railcraft or Foamfix, so I will close it for now. :)
