### ISSUE TITLE
Can't get Dense Ores

### ISSUE THREAD

**Issue by reserveword** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#161]
**General Info (please complete the following information):**
 - Modpack version: 3.4.1
 - Client or server: server
 - Own modifications to the modpack: none

**Describe the bug**
To make Draconic tools/armor I need Dense Diamond/Emerald Ore, but when I dig it with my pickaxe (with Silk Touch), it breaks into diamonds/emeralds instead of dropping dense ores.
There seems to have no way to get dense ores, I suppose?

**To Reproduce**
E.g.:
1. Place down a Dense Diamond Ore
2. Mine it with a Silk Touch pickaxe
3. It breaks into 2 diamonds instead of a Dense Diamond Ore

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Crash-log**
[If applicable, add a crash-log. Usually a "crash-[date]-[time]-server/client.txt"]

**Comment by fabrossmann** [comment]
Thank you for your report!

We also have also experienced this issue reported it to the makers of the original mod. See MinecraftModDevelopmentMods/DenseMetals#25 for more information.

Currently you can get the ore only by using an exchanger. This will change with the upcoming updates, where we will replace the dense ores with ones made by us. You can expect that change probably in the next major update(3.6.x). You will also have the option to convert it to our new method!

**Comment by SanderWxD** [comment]
We've replaced the current Dense Ores mod with a different version that does have silktouch-able dense ores. You will be able to obtain these in the next update!

**Comment by SanderWxD** [comment]
#172
