### ISSUE TITLE
Beef Nugget, Chicken Nugget, Fish Nugget, Mutton Nugget, Pork Nugget, Rabbit Nugget not work in Infernal Furnace

### ISSUE THREAD

**Issue by Erani0** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#162]
**General Info (please complete the following information):**
 - Modpack version: 3.5.0
 - Client or server: MyFTB
 - Own modifications to the modpack: 
 Optifine, Liteloader, Tabbychat

Beef Nugget, 
Chicken Nugget, 
Fish Nugget, 
Mutton Nugget, 
Pork Nugget, 
Rabbit Nugget 
not work in Infernal Furnace

**To Reproduce**
1. Build the Infernal Furnace
2. Activate it with Salis Mundus
3. drop any of this items inside the furnace from top 
4. wait of the nuggets *Spoiler not work*

Iron dust to iron Ingots Work

**Comment by fabrossmann** [comment]
Works fine in 3.5.X. See [video](https://youtu.be/NG56UBfh4B0) 
Please refer to the [FTB Wiki](https://ftb.gamepedia.com/Infernal_Furnace_(Thaumcraft_6)) for more information or ask on our Discord.

**Comment by Erani0** [comment]
Its not working!

[Here a Video](https://youtu.be/2YnYRYpBnRU) test ist self on Server

**Comment by Malien** [comment]
If you're on expert mode, I think it might be because pork and beef are not smeltable in furnaces.

**Comment by Malien** [comment]
From what I've looked into the Thaumcraft API for Craft Tweaker, we can't change recipes just for the infernal furnace. 
But we can [add/remove additional drops to the items](https://github.com/jaredlll08/ModTweaker/blob/1.12/src/main/java/com/blamejared/compat/thaumcraft/handlers/handlers/SmeltingBonus.java). Maybe some kind of compromise can be met to make nuggets available, though I doubt it.
