### ISSUE TITLE
Bewitchment Requires Update

### ISSUE THREAD

**Issue by WalrusSoup** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#165]
**General Info (please complete the following information):**
 - Modpack version: 3.5.1
 - Client or server: both
 - Own modifications to the modpack: none

**Describe the bug**
Current version of bewitchment included has a missing bugfix to address brooms crashing. 
Included version: `bewitchment-1.12.2-0.0.22.49.jar`
Required version: `bewitchment-1.12.2-0.0.22.58.jar`

**To Reproduce**
E.g.:
1. Make bewitchment broom
2. set on ground
3. everything explodes

Reference issue: https://github.com/Um-Mitternacht/Bewitchment/issues/686

**Screenshots**

**Crash-log**

**Comment by saovenn** [comment]
Thanks for your issue.

We will update Bewitchment with 3.6.0 to the latest version 👍

**Comment by SanderWxD** [comment]
^ Updated Bewitchment to version **0.0.22.59** for update 3.6.0.
