### ISSUE TITLE
'Shashing with Wyverns' quest bug.

### ISSUE THREAD

**Issue by kis319** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#166]
**General Info (please complete the following information):**
 - Modpack version: [3.5.1]
 - Client or server: server
 - Own modifications to the modpack: No

**Describe the bug**
'Shashing with Wyverns' quest.
If you create an Energy Cell (Basic) or Portable Tank (Basic) after completing 'The Endest of End Games', the quest will be completed incorrectly.

**To Reproduce**

**Screenshots**

**Crash-log**

**Comment by SanderWxD** [comment]
Fixed in #179. Will be implemented in the next update.

Thank you for the report!
