### ISSUE TITLE
Grass not spreading in the end.

### ISSUE THREAD

**Issue by Lord-Volkner** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#167]
Maybe this is intended behavior, but I'd like to change it back if I can.

These poor endermen are stuck forever in a blighted world. I killed the dragon for them, now it's time to turn their land back into the lush paradise that it use to be. I had no problem doing this in the original FTB:IE, but grass simply isn't spreading in reloaded. Is there a setting somewhere I can change to fix this?

Thanks

**Comment by fabrossmann** [comment]
Grass needs a light level 9 or higher to spread.  This is intended Vanilla [Behaviour](https://minecraft.gamepedia.com/Grass_Block#Spread).

**Comment by Lord-Volkner** [comment]
> Grass needs a light level 9 or higher to spread. This is intended Vanilla [Behaviour](https://minecraft.gamepedia.com/Grass_Block#Spread).

I feel silly. I never thought of that. A stack of feral flare lanterns is already solving the problem. The endermen of the island, thank you.

I think that in the previous Infinity Evolved whatever quarry I used automatically replaced the top endstone with grass instead of dirt.

Thanks again.
