### ISSUE TITLE
Nether Explosions

### ISSUE THREAD

**Issue by Lord-Volkner** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#174]
Not really a bug, but not sure where to ask about this.

Does anyone know how to disable the explosions that come from mining ore in the Nether? ... or at the very least, reduce the frequency? Every other ore I mine causes an explosion. It's extremely annoying and I like to disable/reduce it.

Thanks.

**Comment by Lord-Volkner** [comment]
Never mind. I found it, but if anyone else is looking the setting can be found in the "Netherending Ores" config file.

**Comment by SanderWxD** [comment]
Yes correct, this can be changed in the config file of Netherending Ores. The default explosion rate is 1 in 4 or 25%.
