### ISSUE TITLE
[Bug] Tinkers' Construct Gear Cast Recipes Missing

### ISSUE THREAD

**Issue by Yslohr** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#175]
**General Info : Gear Cast Recipes Missing**
 - Modpack version: 3.5.1
 - Client or server: Both
 - Own modifications to the modpack: None.

**Describe the bug**
No other liquid than gold is accepted for the craft of a Tinkers' Construct Gear Cast, this is a bug because any other Tinkers Construct casts can be created using Brass or Aluminium Brass. I'd like to mention that the clay gear cast is missing too and that I wasn't sure if that was intentional or not. I however understand that the plate cast has been removed because of how the progression functions and that it is intended for you to make it using IC2 or thermal machines etc...

**To Reproduce**
Steps to reproduce the behaviour:
1) Make a working Tinkers Construct Smeltery with a Seared Drain, a Seared Faucet and a Casting Table
2) Alloy/Smelt into the Tinkers' Construct Smeltery Aluminium Brass or the other type of brass (which also is missing a recipe btw although I think that one is intentional?).
3) Place a Thermal Foundation, BuildCraft, EnderIO or any gear which has the gearStone ore dictionary tag onto the Tinkers Construct Casting Table and right click the faucet or provide a Redstone signal to the faucet.
Result: No cast is created, the gear isn't consumed either. I concluded that the recipe is missing, my digging in the scripts confirmed that.

**Screenshots**
And in depth explanation is also provided in the description of the screenshots.
https://imgur.com/a/qPvlRXl
I then checked the TinkersConstruct.zs script and indeed no recipe was created for the gear cast using brass or aluminium brass:
![image](https://user-images.githubusercontent.com/22603163/109305312-d19d0980-783d-11eb-911b-fae28e7c6f88.png)

**Comment by SanderWxD** [comment]
Fixed in #178.
Will be implemented in the next update. Thanks for reporting it.
