### ISSUE TITLE
Extra Utilis generator voids fuel

### ISSUE THREAD

**Issue by gab111** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#181]
- Modpack version: 3.5.1
 - Client or server: Singleplayer
 - Own modifications to the modpack: None
Everything is seen on video. Trying to stack-in fuel in generator causes it to delete item.

https://user-images.githubusercontent.com/51998940/110375460-49dfa800-8052-11eb-870a-49668c647a3c.mp4

**Comment by fabrossmann** [comment]
Hey, this is probably a bug with EU2 and not with the modpack. Normaly I would recomend you to write an issue on the issue page of the mod, but it seems like that EU2 will never get an update, because the author made it archived and thus you are no longer able to write issue.
