### ISSUE TITLE
Moving frame causes small placeables to disappear after 30 seconds

### ISSUE THREAD

**Issue by weedwackerninja** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#184]
**General Info (please complete the following information):**
 - Modpack version: 3.5.1
 - Client or server: Client
 - Own modifications to the modpack: none

**Describe the bug**
When a frame motor moves a frame, any red alloy wire, covers, or wireless redstone devices that move with the frame disappear after 30 seconds. 

**To Reproduce**
1. Place frame motor with power and place frames.
2. Put covers, red alloy cable, wireless redstone, or pretty much any small placeable on the frames.
3. Move the frame and wait 30 seconds. Any frames with covers or any red alloy wire or wireless redstone pieces will vanish.

**Screenshots**
https://drive.google.com/file/d/1QLK2Asgdve7LRGwXrU01CFktrXwPJvjE/view?usp=sharing
Video showcasing issue. Note: if the red alloy wires or the wireless redstone receiver was placed on a moving block with frames behind for support, they would still disappear. It is not just the covers. I do not have this problem in FTB Ultimate Reloaded, and it has made it impossible to set up a frame quarry.

Update:
was able to make a hopper redstone clock instead, but is much more complex than just using wireless redstone. Normal redstone is unaffected.

EDIT: I have been able to set up a frame quarry with a normal redstone clock (hoppers+sticky piston) instead, but it is quite annoying to not be able to use wireless redstone or red alloy wires.

**Comment by fabrossmann** [comment]
Hey this not really a bug with the Modpack, but rather a bug with ProjectRed. It also seems like the issue is known. See MrTJP/ProjectRed#1517.
