### ISSUE TITLE
Tabbychat not working more

### ISSUE THREAD

**Issue by Erani0** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#190]
**General Info (please complete the following information):**
 - Modpack version: 3.6.0
 - Client or server: Client
 - Own modifications to the modpack:
 Optifine, Tabbychat

**Describe the bug**
With the New update is Tabby chat not more Working 
the game crash by start

**Crash-log**
https://paste.myftb.de/piqazujosu

**Comment by SanderWxD** [comment]
I am unable to get TabbyChat working on my client but @Irgendwer01 suggested deleting "[__MixinCompat-0.8__].jar" from your mods folder.

I just checked real quick and you are still able to join servers that have MixinCompat installed when your client has not. So could you try this and post back?

**Comment by Erani0** [comment]
Ty this was the Problem
