### ISSUE TITLE
Tesseracts

### ISSUE THREAD

**Issue by Game2win** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#193]
**General Info (please complete the following information):**
 - Modpack version: [e.g. 3.6.0]
 - Client or server:both
 - Own modifications to the modpack:-

**Describe the bug**
tesseract diconect and drop their channel ply add flux networks

**To Reproduce**
E.g.:
try to use a tesseract leave world and come backj

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Crash-log**
[If applicable, add a crash-log. Usually a "crash-[date]-[time]-server/client.txt"]

**Comment by Einhornyordle** [comment]
If you just need it for energy use Draconic Evolution instead

**Comment by SanderWxD** [comment]
I think it would be better if you report this to the developer of the Tesseract mod. You can create an issue ticket right here: https://github.com/SuperMartijn642/Tesseract/issues

We likely will not be switching to Flux Networks.
