### ISSUE TITLE
Unable to create singleplayer world 

### ISSUE THREAD

**Issue by therealm7** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#195]
[crash-2021-04-14_10.33.07-server.txt](https://github.com/Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded/files/6312683/crash-2021-04-14_10.33.07-server.txt)
Never able to load a world, I have a extremely beefy PC for modded and I am unsure as to why it does not work.

**Comment by Hodel1** [comment]
Did you tried an flat world too (for testing)?
Current Version from curseforge?

System specs? (CPU, Ram, Graphicscard)

The Exception in server tick loop is often because of missing Ram.
I see, you give them 12gb, seems curiously

**Comment by therealm7** [comment]
32 GB ram a 3600 oc'd to 4.3 and a 2060

**Comment by Hodel1** [comment]
Maybe you can open an pregenerated Map?
you can extract that zip file in Documents/Curse/Minecraft/instances/Infinity Evolved Reloaded/saves

[NewWorld.zip](https://github.com/Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded/files/6312820/NewWorld.zip)

**Comment by richardszanyi** [comment]
@therealm7 
Try to delete `options.txt` and `usercache.json` from `c:\Users\{username}\Twitch\Minecraft\Instances\Infinity Evolved Reloaded\`

After that, you should be able to load it. If not:

- Make sure you delete the whole minecraft folder, and reinstall it through curseforge. 
- Try to reinstall Java

Good luck! :)

**Comment by SanderWxD** [comment]
"server tick loop".

Replace your world folder with a recent backup. That should fix the issue, if it doesn't, use an older backup.
