### ISSUE TITLE
RailCraft - Block of Coal Coke cannot be used in Crude Blast Furnace

### ISSUE THREAD

**Issue by richardszanyi** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#197]
**General Info:**
 - Modpack version: 3.6.0
 - Client or server: both
 - Own modifications to the modpack: -

**Describe the bug**
Railcraft Block of Coal Coke - which is a quest reward in the Baking Bad quest - cannot be used in Blast Furnace from Immersive Engineering. 
Also, if you want to make a Block of Coal Coke from 9x Coal Coke, you get the same Railcraft one, which cannot be used either unfortunately.

**To Reproduce**

1. Create a Blast Furnace from Immersive Engineering
2. Get the quest reward from Baking Bad as Coal Coke Block
3. Cannot be used in Blast Furnace

**Comment by Hodel1** [comment]
That coal coke block cannot be crafted back to coal coke, too.
Coal Coke Block cannot be inserted in Blast Furnace here, too

**Comment by saovenn** [comment]
Thanks for your issue

We will add Coal Coke items to our Unification list 👍

**Comment by SirPrimrose** [comment]
Related to this issue, the same quest rewards some creosote oil capsules from IndustrialCraft, which cannot be used to make treated wood and planks like the creosote oil you normally get out of a coke oven. I can open a new issue for this but they are related to the same quest so I figured I would add this note here.

**Comment by SanderWxD** [comment]
Fix will be implemented on in the upcoming update.
