### ISSUE TITLE
No Draconium Ore in End

### ISSUE THREAD

**Issue by Hodel1** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#199]
**General Info (please complete the following information):**
 - Modpack version: 1.6.0
 - Client or server: server
 - Own modifications to the modpack: None

**Describe the bug**
There is no Ender Draconium Ore in End.

**Comment by saovenn** [comment]
Hello Hodel1,

Just looked in SP, there I can find Ender Draconium Ore normally.

Have you checked that there is something configured on your server that could prevent this?


![](https://i.imgur.com/XNk2eMK.jpeg)

**Comment by Hodel1** [comment]
Oh sry, i had forgotten to close the issue. I had yesterday seen draconium ore. It was very very small amount of that :D
