### ISSUE TITLE
Mining Turtle recipe

### ISSUE THREAD

**Issue by EricLulofs** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#200]
Hi,

I'm playing right now the IER Pack in expert mode with a few friends on a dedicated server. However when I try to craft the mining turtle by combining a diamond pickaxe and the turtle it won't let me craft the mining turtle.

Is this maybe a bug in the recipe or isn't it possible any more to make a mining turtle?

**Comment by PumpernickelP** [comment]
I had the same problem. You need to place down the turtle. Put the diamond pickaxe in the first slot top left.
Then you have to type:
Equip 1 left
Then the turtle will become a mining turtle

**Comment by SanderWxD** [comment]
Fixed in #209 :)

**Comment by SanderWxD** [comment]
Fix will be implemented in the upcoming update.
