### ISSUE TITLE
Enderio - Enhanced Machines too weak

### ISSUE THREAD

**Issue by Hodel1** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#202]
**General Info (please complete the following information):**
 - Modpack version: 3.6.0
 - Client or server: both
 - Own modifications to the modpack: None

**Describe the bug**
The Recipes for enhanced alloy smelter, sag mill, etc. are heavy too weak.
The normal machines are heavy updated through receipes. The Enhanced needing an update too.

**Comment by Hodel1** [comment]
Notice: Its on Expert Mode.

Maybe you should make the receipt within the normal machine (exmaple Alloy smelter) with endsteel things, whatever

**Comment by SanderWxD** [comment]
New recipes will be implemented in the upcoming update.
