### ISSUE TITLE
Mod World Control has no crafting recipes

### ISSUE THREAD

**Issue by 2000game** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#210]
**General Info (please complete the following information):**
 - Modpack version: [e.g. 3.6.0]
 - Client or server: both
 - Packmode: both
 - Own modifications to the modpack: none

**Describe the bug**
The Items of the mod "World Control" have no crafting recipes, because the mod developer hasn't finished it. Either add crafting recipes or maybe try this mod "https://www.curseforge.com/minecraft/mc-mods/energy-control". Its basically the same mod but in Beta, or inspire yourself with the recipes of that mod.

**Comment by joinmod** [comment]
same problem... World control has 0 activity from first released alpha on curse (last update is Mar 29, 2019 but in github it's alive), but what about energy control, like what 2000game said? It's same mod but has recipes and all aspects is working, i think... (i didn't tried this mod but saw mod showcase from creator).

**Comment by SanderWxD** [comment]
I've tested the mod. We will switch to Energy Control in the next update. Thank you for reporting it.
