### ISSUE TITLE
Cant complete Common + Cultivated = Diligent quest 

### ISSUE THREAD

**Issue by serbaut** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#219]
**General Info
 - Modpack version: 3.6.0
 - Packmode: expert

I have tried drones from regular apiaries and gendustry.

![image](https://user-images.githubusercontent.com/68637/121784919-119eb700-cbb7-11eb-81a8-e3dcde34c98c.png)

**Comment by daniel-majonica** [comment]
I can confirm this is a real issue, please fix

**Comment by SanderWxD** [comment]
Fixed in #229
