### ISSUE TITLE
Energy Controll Range Upgrade

### ISSUE THREAD

**Issue by Erani0** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#220]
**General Info (please complete the following information):**
 - Modpack version: 3.7.0
 - Client or server: Server
 - Packmode: expert

Energy Controll Range Upgrade is not craftable the 10K Collant Cell from crafting 
Have 1 NBT Tag and the recipe is with no NBT Tag

**Screenshots**
https://ibb.co/7XDk96n

**Comment by SanderWxD** [comment]
Will be added in the upcoming update
