### ISSUE TITLE
Thaumcraft 6 Extension Thaumic Augmentation

### ISSUE THREAD

**Issue by Erani0** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#222]
Since Thaumcraft 6 is not 100% finished, unfortunately a lot is missing like the Eldritch dimension

I found a mod here that e.g. brings this dimension back into play in a different way and of course even more

The mod is called [Thaumic Augmentation ](https://www.curseforge.com/minecraft/mc-mods/thaumic-augmentation)

Of course I tested the mod beforehand and it works as it should, I would be happy to hear from you.

Here a Screenshot from the buildung scructure
![2021-06-15_06 02 48](https://user-images.githubusercontent.com/76605008/121993326-92220b00-cda3-11eb-94f3-22fbf1a2c8dd.png)

With best regards

**Comment by SanderWxD** [comment]
We already have this mod on our schedule and will be added in the next **major** update.

**Comment by Erani0** [comment]
The next Major Update is Long Time Released and no added.

**Comment by saovenn** [comment]
Major updates start with the first number, which means the next major update would be 4.0.0
