### ISSUE TITLE
Cant craft Ender pearl dust for the portal gun

### ISSUE THREAD

**Issue by krustymk** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#227]
**General Info (please complete the following information):**
 - Modpack version: [3.70
 - Client 
 - Packmode: Normal
 - Own modifications to the modpack: none

**Describe the bug**
Cant craft Ender pearl dust for the portal gun (Tried Immersive Engineering Crusher but no joy)

**To Reproduce**
Build Immersive Engineering Crusher
throw ender pearl in
ender pearl out, no dust

**Comment by SanderWxD** [comment]
Thank you for reporting this. I've replaced the Enderpearl Dust with one that is craftable in #230. It will be implemented in the upcoming hotfix.
