### ISSUE TITLE
[Recipe Bug]Creative Jetpack recipe

### ISSUE THREAD

**Issue by kis319** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#236]
**General Info (please complete the following information):**
 - Modpack version: 3.7.1
 - Client or server: Client
 - Packmode: expert
 - Own modifications to the modpack: Add LagGoogles and TickCentral Mods

**Describe the bug**
Recipe Bug
Can't use the Creative Jetpack recipe in Survival.
This recipe can only be used if the JetPlate was obtained in Creative Mode and is charged.

**To Reproduce**

**Screenshots**

**Crash-log**

**Comment by SanderWxD** [comment]
Thank you for creating a ticket. The recipe has been fixed in #247 and will be implemented in the next update.
