### ISSUE TITLE
Inventory sorter

### ISSUE THREAD

**Issue by Krougal** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#239]
I'm not making a full report for this, it's an old bug and it's been documented on Botania's issues (it was fixed in newer versions but not backported it appears).
If you use CPW's inventory sorter to sort and you've got a Botania flower pouch, all your stored flowers will disappear.
As you've also got inventory tweaks (which does not have this issue) the mod is redundant to boot.
I'd suggest removing it.

**Comment by saovenn** [comment]
Hello,

The InventorySorter mod was added by Sander for testing and was forgotten to remove until now, I've added it for the next patch

**Comment by fabrossmann** [comment]
Removed in 3.8.0
