### ISSUE TITLE
No expert recipe for Thermoelectric Generator

### ISSUE THREAD

**Issue by mrthommaso** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#245]
- Modpack version: 3.8.0
 - Client and server
 - Packmode: expert
 - Own modifications to the modpack: none

**Describe the bug**
There is no recipe for Thermoelectric Generator in expert mode.

**To Reproduce**
Search recipe for Thermoelectric Generator

Fixed locally by adding this to ImmersiveEngineering.zs based on IE 1.7.10:
#Thermoelectric Generator
recipes.remove(<immersiveengineering:metal_device1:3>);
recipes.addShaped(<immersiveengineering:metal_device1:3>, [
    [<ore:ingotConstantan>, <immersiveengineering:metal_device0:1>, <ore:ingotConstantan>],
    [<ore:ingotEnderium>, <immersiveengineering:metal_decoration0:2>, <ore:ingotEnderium>], 
    [<ore:ingotEnderium>, <ore:ingotEnderium>, <ore:ingotEnderium>]
]);

**Comment by SanderWxD** [comment]
Thank you for opening your ticket. The recipe has been added with #246 and will be included in the next update!
