### ISSUE TITLE
[Progression bug / stopper] Railcraft Rock Crusher doesn't accept RF / won't connect to fluxduct or similar

### ISSUE THREAD

**Issue by P1neapplecak3** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#253]
**General Info (please complete the following information):**
 - Modpack version: 3.9.0
 - Client or server: Both
 - Packmode: Expert, should be both
 - Own modifications to the modpack: Removed BoP, added OTG

**Describe the bug**
The Rock Crusher quest states, "(...) uses RF to crush blocks.". Neither Fluxducts or IE wire connector to the multiblock / supplies it with energy.

![grafik](https://user-images.githubusercontent.com/47895077/162800173-6edf8bc5-2fdc-42f3-b0fc-571d6f7a2c71.png)

**To Reproduce**
Steps to reproduce the behavior: Build a Rock Crusher. Place a Fluxduct next to it. The duct will not connect to the Rock Crusher, preventing it from crushing Obsidian.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/47895077/162799224-fd0e2fb9-8358-485f-8c48-b69f846daf64.png)

![grafik](https://user-images.githubusercontent.com/47895077/162799389-312c3079-51e6-4176-a19b-2ad88f35c2b2.png)

Relevant Reddit posts I've found regarding the issue :

https://www.reddit.com/r/Tekxit/comments/cg9pl0/rock_crusher_power/

https://www.reddit.com/r/Tekxit/comments/cqkiht/how_do_i_power_a_rock_crusher/

(The wiki article linked also says that RF is required to power the rock crusher)

**Comment by SanderWxD** [comment]
Looks like I supplied the wrong information in the quest. Railcraft machines need to be powered by Railcrafts own energy. This can be obtained with a Flux Transformer. There is a quest explaining the Flux Transformer as well.

**Comment by SanderWxD** [comment]
Fixed in #257, will be implemented in the next update
