### ISSUE TITLE
Last Update remove all 1024K+ me cells

### ISSUE THREAD

**Issue by Erani0** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#254]
**General Info (please complete the following information):**
 - Modpack version: [e.g. 3.9.0]
 - Client or server: server
 - Packmode: testet on expert
 - Own modifications to the modpack:
none
**Describe the bug**
Last Update remove all 1024K+ me cells

**Comment by SanderWxD** [comment]
We have indeed received reports (3 actually, including yours) of the contents of Extra Cells Storage Cells being wiped after installing update 3.9.0. 

![image](https://user-images.githubusercontent.com/71182068/166219633-7d6d1286-f5af-43bb-8e11-f0607be8dfcd.png)
At the top of the update-message for version 3.9.0, I recommended everyone to back-up their worlds before installing. So if you would now like to restore the contents of your Extra Cells Storage Cells, you can downgrade your client, load the back-up you made, and use the ME IO-Port to transfer the contents of your Extra Cells Storage Cells onto the default Applied Energistics Storage Cells to then update your client again.

**Comment by Erani0** [comment]
As I wrote, I play on a server where the operators say they had no idea what was changed in the update.  And this warning does not exist in your launcher.  Please do not remove any mod immediately for the future, rather deactivate the recipes first.  Because Mojangplsfix and Saoven simply apply the updates to the server and ignore problems that arise afterwards.

**Comment by SanderWxD** [comment]
"And this warning does not exist in your launcher" but I don't even have my own launcher...?

I understand the frustration that this must have caused but the methods and ideology of the staff members on your server aren't up to me to decide. 
We will sadly not stop to make changes in the best interest of the modpack.

**Comment by Erani0** [comment]
This was a translation error. I use the launcher from the server network where I play.

I fully understand that you want the best for the modpack, but then please also be considerate of players who play on a server for the next time.

**Comment by SanderWxD** [comment]
"This was a translation error. I use the launcher from the server network where I play." then it's even less of my problem to be honest. Nowhere do I suggest or encourage players to use third party launchers to run IE:R. You cannot hold me accountable for their decisions in what to share with their users or not.
