### ISSUE TITLE
Caught exception from Just Enough Items (jei)

### ISSUE THREAD

**Issue by PHI-AM** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#255]
**General Info (please complete the following information):**
 - Modpack version: 3.9.0
 - Client or server: Client
 - Packmode: [normal]
 - Own modifications to the modpack: None

**Describe the bug**
I downloaded the pack for the first time and when I launch the game I get the exception above. Deleted it and downloaded it again but still same behaviour.

**Crash-log**
[If applicable, add a crash-log. Usually a "crash-[date]-[time]-server/client.txt"]
[crash-2022-06-06_00.36.57-client.txt](https://github.com/Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded/files/8840911/crash-2022-06-06_00.36.57-client.txt)

**Comment by SanderWxD** [comment]
```
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
...
Memory: 516787000 bytes (492 MB) / 3817865216 bytes (3641 MB) up to 3817865216 bytes (3641 MB)
```

You have 3,6 GB (the default) amount of RAM allocated to your client. Our modpack needs a minimum of 5 GB, but an optimum of 8 GB in order to launch.

**Comment by PHI-AM** [comment]
Oh, my bad sorry. People that can read clearly got an advantage.^^
