### ISSUE TITLE
Railcraft rolling machine missing plate recipes.

### ISSUE THREAD

**Issue by bookerthegeek** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#261]
**General Info:**
 - Modpack version: 3.9.0
 - Client or server: Both?
 - Packmode: Both
 - Own modifications to the modpack: None so far

**Describe the bug**
Any metal not native to Railcraft does not have an ingot -> plate recipe in the rolling machine.

**To Reproduce**
1. Load Pack
2. Put down rolling machine, either powered or not
3. Make Any plate from metal from vanilla Minecraft or Railcraft, Get a plate.
4. Attempt to make a plate from any metal NOT native to vanilla or Railcraft.

**Comment by SanderWxD** [comment]
I've just tested what you reported, but I'm afraid I cannot replicate the issue.
Ive tested Railcraft: 
![2PdGJKx](https://user-images.githubusercontent.com/71182068/204106157-14326d2d-b0e4-4701-8fe9-1edeb60e2c3b.png)

Thermal Foundation:
![ca9cguF](https://user-images.githubusercontent.com/71182068/204106166-71784ca2-fdef-46f6-95bc-ecab3bff90a2.png)

And IndustrialCraft2:
![HrIBTdD](https://user-images.githubusercontent.com/71182068/204106176-4638931b-d37e-4a8a-a49c-f63d07a7c7ef.png)

Could you perhaps specifiy exactly which mod's ingots you are having issues with?

**Comment by bookerthegeek** [comment]
Specifically, aluminum.

**Comment by SanderWxD** [comment]
Aha, I see now. Apparently plates like Electrum, Enderium and Lumium cannot be rolled in a Rolling Machine either.
Sadly it turns out, that Railcraft is one of the few mods that does not offer support for CraftTweaker. Meaning I cannot fix this issue sadly, only the developers of Railcraft and CraftTweaker can.
