### ISSUE TITLE
[Suggestion]:Enable Thaumic JEI aspect information

### ISSUE THREAD

**Issue by No-steve** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#263]
**General Info (please complete the following information):**
 - Modpack version:4.0.0
 - Client or server:Client
 - Packmode: both
 - Own modifications to the modpack:no

As the title say

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Comment by SanderWxD** [comment]
Seems already enabled ¯\_(ツ)_/¯

**Comment by No-steve** [comment]
Like this:
![OIP](https://github.com/Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded/assets/105639186/69ce9ef2-9dd9-4018-90a2-6e23f8bd2859)
