### ISSUE TITLE
Invalid quest conditions

### ISSUE THREAD

**Issue by DAmNRelentless** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#264]
**General Info:**
 - Modpack version: 4.0.0
 - Client or server: both
 - Packmode: expert

**Describe the bug**
The quests `Drill From the Heavens` and `Who Took My Mountain?` are mixed up. In order to craft the Quarry, you need a Laser Drill but the quest conditions unlock the Quarry quest first.

**To Reproduce**
1. Complete the `Wazer Wifle` quest
2. See that the Quarry quest is unlocked
3. See that the Laser Drill Quest needs the Quarry quest

**Comment by SanderWxD** [comment]
Fix wil be implemented in the next release.
