### ISSUE TITLE
Logistic Pipes Missing Recipe´s

### ISSUE THREAD

**Issue by ScreamTrip** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#268]
**General Info (please complete the following information):**
 - Modpack version: 4.0.0
 - Client or server: Both
 - Packmode: both
 - Own modifications to the modpack: none

**Describe the bug**
Logistic Pipes. The recipe for the RF / EU Power Providers are Missing so it isnt craftable

**To Reproduce**
E.g.:
1. Go to JEI
2. Try to Search for an Recipe for the RF Power provider from Logistic Pipes
3. See that there will not be an recipe

**Screenshots**
Sorry didn´t make sense.

**Comment by saovenn** [comment]
The current version of Logistics Power Providers does not come with a recipe. They function similarly to the Logistic Power Junction, with the distinction that Power Providers can solely store Logistic Power and are unable to convert any other forms of energy into LP. Moreover, the providers do not possess any built-in functionalities in this version, rendering it pointless to create a recipe for them.
