### ISSUE TITLE
Buildcraft assembly table + lasers not working. Using the energy converter mod.

### ISSUE THREAD

**Issue by EnterOriginal** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#276]
**General Info (please complete the following information):**
 - Modpack version:: 4.3
 - Client or server: client
 - Packmode: [normal,expert,both] Expert
 - Own modifications to the modpack: Optifine

**Describe the bug**
Using the energy converter mod as described in quest book, the assembly table and lasers still do not accept energy and thus do not function. even using straight BC engines to power them it will not work. I can see the energy transfer through the pipes when just connecting them but that is it. I've used kinesis pipes on the lasers too, used multiple different pipes and straight immersive cables aswell. 

**To Reproduce**
E.g.:
2. Try to '...'
3. See error.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
![Screenshot (7)](https://github.com/Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded/assets/45597563/4596f75e-733e-4d94-ae0d-2a67de6909b8)

**Crash-log**
[If applicable, add a crash-log. Usually a "crash-[date]-[time]-server/client.txt"]

**Comment by SeigneurNecron** [comment]
From my experience, the problem is most probably the position of the lasers relative to the table. Lasers must be placed in a cone - or rather a pyramid - starting from the table. Did you try reducing the distance on the Y coordinate and/or increasing the distance on the X/Z coordinates?

**Comment by EnterOriginal** [comment]
Was actually able to resolve it by putting the lasers above the table pointing down to it. For some reason that fixed it.

**Comment by SeigneurNecron** [comment]
yeah, the pyramid area above the table also works.

**Comment by EnterOriginal** [comment]
Used to be that you could place them pretty much anywhere, even with blocks in between it would work, hence my confusion as to why it wasn't working now. Thanks for the quick reply tho.

**Comment by SeigneurNecron** [comment]
You're welcome. It also surprised me when I played that version after playing the original FTB IE years ago. Must be a change from Buildcraft itself. I'm not part of the dev team, I'm just an other player. I saw your message in the "Infinity Evolved: Reloaded" Discord's Github channel. ;)
