### ISSUE TITLE
Cannot download the new 3.0.0 version off twitch launcher

### ISSUE THREAD

**Issue by NickCG01** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#53]
It is saying "This modpack requires a dependency that is missing or no longer available. Missing Addon ID: 268655"

**Comment by SanderWxD** [comment]
Have you tried deleting and reinstalling the modpack?
The mod with this particular ID is not part of the modpack.

**Comment by SanderWxD** [comment]
No response, closing ticket.
