### ISSUE TITLE
Aluminum and Bauxite not generating

### ISSUE THREAD

**Issue by TristanKing0** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#69]
Neither are generating in the world on my server, even when I set enabled to true in the Thermal Foundation config.

**Comment by saovenn** [comment]
Hello,

What Modpack version do you currently play on?

**Comment by SanderWxD** [comment]
We sadly haven't heard from you yet, but in version 3.1.0, the worldgen was adjusted to include Aluminum ore in the worldgen. If you update(d) your client, you can go to unexplored/unchunkloaded parts of the overworld or mining world to find aluminum ore.
Creating a completely new world will also work ofcourse.
