### ISSUE TITLE
Potential Quality of Life Improvements

### ISSUE THREAD

**Issue by ElektroKill** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#81]
First of all, thank you for making this pack.

I have some quality of life improvements that could make the experience better.

Mods which could be added and reasons:
- Phosphor - Phosphor is an optimization mod for Minecraft which improves performance by optimizing the lightning engine used by Minecraft. This could help increase the average FPS in-game on some machines.
- Hwyla - it is required for Wawla to work properly.
- WailaHarvestability - allows players to see if they are able to mine a block in the hwyla/waila information prompt.
- CraftingTweaks - this mod adds a couple of additions to the crafting table GUI making crafting in bulk much more fun.

I hope you are able to address some of these suggestions :)

**Comment by SanderWxD** [comment]
Hello, Thank you for making these suggestions.

- Phosphor seems promising. I'll test it's compatibility with the modpack and likely add it in the next update.
- Hwyla;
- WailaHarvestability, alongside Wawla, have been replaced by The One Probe recently due to the latter having more features and options and it seemed like the superior alternative so we will likely not be switching back.
- CraftingTweaks looks like a nice QoL mod and will likely be added.

**Comment by ElektroKill** [comment]
Thanks for looking into Phosphor and CraftingTweaks, however since I greatly prefer Hwyla over OneProbe, and I know many other modded players do too.  What about including both but allowing the user to choose which one they prefer?

I prefer Hwyla over OneProbe since it in my gameplay experience tends to have more widespread support from other mods and also shows more information. This is however my opinion.

**Comment by angrych33s3puff** [comment]
Hi there! 
If a user wanted hwyla/wailia/another one like that couldn't they just add it themselves? Isn't a client side mod?

**Comment by SanderWxD** [comment]
We sadly have conflicting experiences then but what angrych33s3puff says is correct, you can just remove and replace The One Probe with whatever other mod you like since they are client sided and not on servers.

Installing both would become messy and is, in my opinion, unnecessairy.

**Comment by ElektroKill** [comment]
Ok, I understand your reasoning :)
