### ISSUE TITLE
Issue with lettuce mutation.

### ISSUE THREAD

**Issue by cavinnhobbes** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#89]
**General Info (please complete the following information):**
 - Modpack version: 3.3.0
 - Client or server: Both (config issue)
 - Own modifications to the modpack: None.

**Describe the bug**
While progressing through the crop mutations from agricraft, it was found that the mutation between daisy and celery to make lettuce was being unusual and strange, according to the quest book crop quests, this is the way to make them, however JEI does not show the 'recipe' for the mutation, nor does, after lengthy testing, the mutation occur at all.

Deep delves into the config for agricraft reveals a simple mistype, as it is calling for "harvestcraft:daisy_plant" instead of what should be "vanilla:daisy_plant within 'config\agricraft\json\defaults\mod_harvestcraft\mutations\lettuce_mutation.json", It is unknown if there are any other mistypes of this type occur throughout the agricraft mutations

**To Reproduce**
E.g.:
1. Plant within crop sticks, daisy seeds and celery seeds, and a crossed crop sticks in between the two.
2. For convenience, you may want to set doRandomTickSpeed to a high value.
3. You will seemingly be unable to get lettuce.

**Screenshots**
What is currently there.
![image](https://user-images.githubusercontent.com/22580476/100969020-6b377200-3500-11eb-9ec3-fa2d20f4b2f9.png)

What has been tested to have worked.

![image](https://user-images.githubusercontent.com/22580476/100969004-64106400-3500-11eb-90f0-9e02c509543a.png)

**Comment by SanderWxD** [comment]
Thanks for reporting this bug.
This was a typo on my part.

MojangPlsFix already fixed this bug and it will be implemented next update.
Update will come as soon as Curseforge sorts out their problems with the launcher and upload/approval service.

**Comment by fabrossmann** [comment]
fixed in #85
